### PR TITLE
Feature: Add Stackblitz link to the issue template for interactive examples

### PR DESCRIPTION
**Pull request by alexbjorlig**
**Feature Request**
To improve the user experience when reporting issues or seeking help, I propose adding a Stackblitz link with a pre-configured Radix environment to the GitHub issue template. This will enable users to create and share minimal reproducible examples with ease.

**Benefits**
- Simplifies the process of sharing code examples when reporting issues or asking questions.
- Encourages users to provide reproducible examples, helping maintainers diagnose and resolve issues more effectively.
- Offers users an interactive environment to experiment with Radix without setting up a local development environment.

**Implementation**
I have prepared a basic Stackblitz template for Radix [here](https://stackblitz.com/edit/node-rvtbvk?file=package.json). If approved, I will add this link to the appropriate issue template(s). Any suggestions or refinements are welcome. Thank you for considering this feature request!

### CODE REVIEW

**Comment by TGlide** [comment]
Hi @alexbjorlig thank you for this PR! Amazing idea. My only question is, would we be able to make sure the template is automatically up to date with the latest radix-svelte version? Otherwise, we should specify the user to make sure they change the version on the stackblitz repro.

**Comment by alexbjorlig** [comment]
> Hi @alexbjorlig thank you for this PR! Amazing idea. My only question is, would we be able to make sure the template is automatically up to date with the latest radix-svelte version? Otherwise, we should specify the user to make sure they change the version on the stackblitz repro.

That's a really good point. Let me investigate our options here, and I will get back to you 🤔

**Comment by alexbjorlig** [comment]
Ok, after researching a bit I think simply adding `latest` in the package.json might be the simplest possible solution 🤔

**Comment by TGlide** [comment]
> Ok, after researching a bit I think simply adding `latest` in the package.json might be the simplest possible solution 🤔

Still, there's the package-lock. But I think it's fine, probably. 

We could also hard set the versions (besides radix-svelte) and omit package-lock, but I;m not sure if that's a good idea. Anyways, thanks for investigating! I'll go ahead and approve this, we can modify it in the future if we need to.

**Pull request merged**
